### ISSUE TITLE
The Liveleak catetegories have changed, 1.4.0 files does not work due to link to old catetegories

### ISSUE THREAD

**Issue by mikasand** [Botster/plugin.video.liveleak#3] opened 2020-06-06 11:54 UTC
The Liveleak categories included in 1.4.0 are no longer valid.
Please update to new Liveleak categories. I wish I could update my self but have too little knowledge about coding. 

Old Categories:
msgid "Featured"
msgid "News & Politics"
msgid "Yoursay"
msgid "Must See"
msgid "Ukraine"
msgid "Middle East"
msgid "Entertainment"
msgid "WTF"
msgid "Russia"

The new ones different, please check up
examples:
featured(?)
fail
news
recent 
must see
wtf
humor
cute 
amazing

**Comment by Botster** [comment] 2020-06-06 14:14
The Liveleak categories did not change between v1.3.5 and v1.4.0. They were working before the update, and I have just tested them and they still work.

There are some new categories on the site that aren't listed in categories. But, the addon's categories do work. What exactly do you mean by, "don't work"? What don't they do?

I don't know where you got that list for categories. What I see on the main page of the site is:
News & Politics
Law Enforcement
Must See
Weather
Entertainment
Yoursay
Liveleakers
More...

**Comment by mikasand** [comment] 2020-06-07 08:57
Please see some screenshots from Liveleak new design and also Kodi Loginformation.


![liveleak new categories marked in blue](https://user-images.githubusercontent.com/66517855/83964467-9fadd680-a8ad-11ea-8ceb-6cee182e4a66.png)
![liveleak error](https://user-images.githubusercontent.com/66517855/83964470-a50b2100-a8ad-11ea-9ef5-52995eecc004.png)
![log 1 of 2 for category Ukraine](https://user-images.githubusercontent.com/66517855/83964471-a9373e80-a8ad-11ea-8201-fe07663a6a8f.png)
![log 2 of 2 for category Ukraine](https://user-images.githubusercontent.com/66517855/83964475-ac322f00-a8ad-11ea-8881-7822d462d3e1.png)

**Comment by Botster** [comment] 2020-06-07 12:00
Thank you for providing those error reports. That tells me what the issue is.
It does not have anything to do with the categories. And, the issue has been fixed in v1.4.1 which is currently awaiting approval for merging into the official Kodi plugin repository.

Now, regarding the categories. Is it possible that those are your favored categories, and you get those specific ones because you are logged in? I ask because as a non-logged Guest, I get what this pic shows.
![Screenshot_20200607_075329](https://user-images.githubusercontent.com/607940/83968098-cf9cb000-a894-11ea-9669-0ce6110d1bda.png)

**Comment by Botster** [comment] 2020-06-07 12:43
I should have mentioned that you can download the new fix now if you wish. Go to the Code tab, click the "Clone or download" button, download the ZIP file. Unzip it and place it in the liveleak plugin folder. If you're on Windows, a user posted instructions on how to do this here:
https://github.com/Botster/plugin.video.liveleak/issues/2#issuecomment-636433933

**Comment by mikasand** [comment] 2020-06-07 16:36
Hello,
I can not even login to my Liveleak account any longer, using windows pc and Chrome webbrowser.

But normally I use Kodi on my Android TV.

Maybe liveleak changed their site so it is working differently depending on country. I live in Europe (Sweden), maybe itheir site work in other ways in UK or US

Thanks anyway for fixing it, I will update plugin when available. If any troubles with 1.4 1 I will let you know!

Regards Mikael



Den 7 juni 2020, kI 14:43, Botster <notifications@github.com<mailto:notifications@github.com>> skrev:

I should have mentioned that you can download the new fix now if you wish. Go to the Code tab, click the "Clone or download" button, download the ZIP file. Unzip it and place it in the liveleak plugin folder. If you're on Windows, a user posted instructions on how to do this here:
#2 (comment)<https://github.com/Botster/plugin.video.liveleak/issues/2#issuecomment-636433933>

**Comment by mikasand** [comment] 2021-03-13 10:07
Hello
Since kodi 19 update Liveleak does not work anylonger.
Will this plugin be updated to work with the updated kodi 19?


Thanks, Mikael



________________________________
Från: Mikael Sandberg ***@***.***>
Skickat: den 7 juni 2020 18:36
Till: ***@***.*** ***@***.***>
Kopia: ***@***.*** ***@***.***>; ***@***.*** ***@***.***>
Ämne: Re: [Botster/plugin.video.liveleak] The Liveleak catetegories have changed, 1.4.0 files does not work due to link to old catetegories (#3)

Hello,
I can not even login to my Liveleak account any longer, using windows pc and Chrome webbrowser.

But normally I use Kodi on my Android TV.

Maybe liveleak changed their site so it is working differently depending on country. I live in Europe (Sweden), maybe itheir site work in other ways in UK or US

Thanks anyway for fixing it, I will update plugin when available. If any troubles with 1.4 1 I will let you know!

Regards Mikael



Den 7 juni 2020, kI 14:43, Botster ***@***.******@***.***>> skrev:

I should have mentioned that you can download the new fix now if you wish. Go to the Code tab, click the "Clone or download" button, download the ZIP file. Unzip it and place it in the liveleak plugin folder. If you're on Windows, a user posted instructions on how to do this here:
#2 (comment)<https://github.com/Botster/plugin.video.liveleak/issues/2#issuecomment-636433933>

**Comment by Botster** [comment] 2021-03-15 20:02
> Hello Since kodi 19 update Liveleak does not work anylonger. Will this plugin be updated to work with the updated kodi 19? Thanks, Mikael

I am unsure what you mean by it doesn't work. The Liveleak plugin has actually not even been available for Kodi 19 (Matrix). I have just submitted a request for it to be pulled into the Matrix repository. I do not yet have sane access to a Kodi 19 version for testing, so, hopefully it will work.

**Comment by Botster** [comment] 2021-03-20 12:35
The plugin is now available for Kodi 19. I am closing this issue. Please feel free to reopen it if you experience any issues.

(Note: Kodi 19 forces a container refresh after playing a media file. This causes the video listing to be re-fetched and the cursor placed at the top of the list. I can do nothing about that.)

**Closed by Botster** 2021-03-20 12:35 UTC
